### ISSUE TITLE
WiFi Broken Again?

### ISSUE THREAD

**Issue by adam-m-jcbs** [denysvitali/linux-on-pixel-c#11]
I seem to be having issues similar to those outlines in #3 .  But for me the wireless still doesn't work.  I used the get_firmware script and your latest v4.19 boot img (I couldn't manage to make a signed image on my own).

I love this project!  Everything is working but wireless (I can get by with ethernet in a pinch).  I don't think I'm quite the kernel hacker you are.  Any pointers or advice on getting my wireless up would be greatly appreciated!  Also, please let me know what info you might need.  Happy to carry out tests and do diagnostics.

**Comment by denysvitali** [comment]
Hello there!  
Thank you for opening this issue!  
  
Can you please try with one of the attached boot images?  

- [boot-5.5-rc5.zip](https://github.com/denysvitali/linux-on-pixel-c/files/4051437/boot-5.5-rc5.zip)
- [vartom.zip](https://github.com/denysvitali/linux-on-pixel-c/files/4051458/vartom.zip) 

Out of curiosity, which rootfs are you using?

**Comment by adam-m-jcbs** [comment]
Thanks for the reply! I'm quite busy at the moment, so it may be a while before I get back to you. But I greatly appreciate the files.

I adapted the Arch Linux rootfs that can be built with the scripts linux-on-pixelc provides (something like rootfs_builder). The default didn't work, but it was a good enough starting point to build a Arch Linux rootfs that runs and appears to be stable as long as I don't run up against some firmware I seem to not have. I got the brcm stuff from Google as recommended. And I built Mesa with tegra turned on.

**Comment by adam-m-jcbs** [comment]
I'm curious: is `boot.img` just a convention, or is it mandatory for the image to be named `boot.img`?  I prefer to give mine slightly more illuminating names.

**Comment by adam-m-jcbs** [comment]
Update: 

`boot-5.5-rc5.zip` fails.  I boot into it via `fastboot` and it seems to just get the backlight going before hanging a bit, then it reboots.

`vartom.zip` fails even before booting.  I get (please forgive the `zsh` cruft):

```
fastboot flash boot boot-vartom.img             ✔  16:09:55
Sending 'boot' (22263 KB)                          OKAY [  0.602s]
Writing 'boot'                                     (bootloader) writing flash
FAILED (remote: 'image not multiple of block size')
fastboot: error: Command failed
```

Once I flash back the `v4.19-smaug-data` image I got from you, my very nearly-perfect OS is running.  Works great, just would be extremely useful with wifi.  I could use it as a great development productivity tool.  As of now, too many spaces just don't even have ethernet available, or I'm on the go.

If there's more diagnostics I can do, or more info you'd like, lemme know!  Really appreciate you looking into this.

**Comment by adam-m-jcbs** [comment]
Alternatively, if I could share my laptop's connection over usb, that would be a pretty workable solution for the moment.  Not sure how to get started with doing that securely and such.

**Comment by denysvitali** [comment]
[boot-5.1-rc2.zip](https://github.com/denysvitali/linux-on-pixel-c/files/4081783/boot-5.1-rc2.zip)


This should work. We are working on bringing 5.5-rc6, but it doesn't seem to work. Join us at https://telegram.me/pixelclinux

**Comment by adam-m-jcbs** [comment]
Note: The issue ultimately ended up being one, apparently, with my `netctl` package.  Switching to `NetworkManager`, I was able to connect over wifi without issue.

Much thanks to @denysvitali for helping me debug this.
