### ISSUE TITLE
Lightbar doesn't work

### ISSUE THREAD

**Issue by denysvitali** [denysvitali/linux-on-pixel-c#8]
With our `4.14.0-rc6` kernel (and previous), the lightbar doesn't work. Apparently there are some changes in the `mfd/cros*` drivers (`cros_ec_lightbar.c`) that are missing. We only need to port them to our `linux-smaug` kernel from Google's `linux-smaug`.

**Comment by denysvitali** [comment]
I'm trying to fix it on [linux-smaug/lightbar-fix](https://github.com/denysvitali/linux-smaug/tree/lightbar-fix) branch. I still can't figure out why the request messages are too big.  
  
```
[    3.134687] iommu: Adding device cros-ec-ctl.0.auto to group 58
[    3.163862] cros-ec-i2c 1-001e: Chrome EC device registered
[    4.469298] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    4.476084] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    4.482864] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    4.489646] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    4.496427] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    4.503206] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    4.509986] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    4.682811] iommu: Adding device cros-ec-accel.0 to group 74
[    4.688726] iommu: Adding device cros-ec-gyro.0 to group 75
[    4.694437] iommu: Adding device cros-ec-mag.0 to group 76
[    4.700049] iommu: Adding device cros-ec-light.0 to group 77
[    4.705829] iommu: Adding device cros-ec-prox.0 to group 78
[    4.711519] iommu: Adding device cros-ec-activity.0 to group 79
[    4.717553] iommu: Adding device cros-ec-ring.0 to group 80
[    4.723215] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    5.443276] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    5.493140] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    5.545142] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    5.597137] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    5.649134] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    5.701134] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    5.750081] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[    5.801138] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
[   37.090989] cros-ec-i2c 1-001e: request of size 194 is too big (max: 120)
```

Relevant files:
- https://android.googlesource.com/kernel/tegra/+/android-tegra-dragon-3.18-oreo-r6/drivers/mfd/cros_ec_i2c.c
- https://github.com/denysvitali/linux-smaug/blob/lightbar-fix/drivers/platform/chrome/cros_ec_proto.c

Pinging some folks who authored some commits in the chrome platform (Chromium members?), maybe we can get some help over here: @groeck @bleungatchromium @drinkcat

**Comment by denysvitali** [comment]
Fixed in [4.15-rc8-feature-lightbar](https://github.com/denysvitali/linux-smaug/tree/4.15-rc8-feature-lightbar). The fix is now merged in [4.15-rc8](https://github.com/denysvitali/linux-smaug/tree/4.15-rc8).

**Comment by vartom** [comment]
Try to adapt this
https://github.com/vartom/android_kernel_smaug/commit/65ed23383137dfc9b191298a552aab787c57268a

**Comment by denysvitali** [comment]
I'll look into it. Thank you 👍
